# Generated by Django 5.1.7 on 2025-04-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookimage_book_alter_bookimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
