# Generated by Django 5.1.7 on 2025-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(default=1, upload_to='book_images/'),
            preserve_default=False,
        ),
    ]
