# Generated by Django 5.1.7 on 2025-04-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_bookimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(default=1, upload_to='book_images/'),
            preserve_default=False,
        ),
    ]
