# Generated by Django 5.1.7 on 2025-04-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_alter_bookimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Kitob",
                "verbose_name_plural": "Kitoblar",
            },
        ),
        migrations.AlterModelOptions(
            name="bookimage",
            options={
                "verbose_name": "Kitob rasmi",
                "verbose_name_plural": "Kitob rasmlari",
            },
        ),
    ]
