# Generated by Django 5.1.7 on 2025-04-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_alter_book_options_alter_bookimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
