# Generated by Django 5.1.7 on 2025-04-14 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_alter_book_options_alter_bookimage_options"),
        ("review", "0002_alter_rating_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(fields=["stars"], name="review_rati_stars_74e323_idx"),
        ),
    ]
