# Generated by Django 5.1.7 on 2025-04-12 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_alter_bookimage_image"),
        ("wishlist", "0002_remove_wishlist_book_wishlist_book"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "book")},
        ),
    ]
