# Generated by Django 5.1.7 on 2025-04-12 17:48

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "wishlist",
            "0004_alter_wishlist_unique_together_remove_wishlist_book_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishlist",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
