# Generated by Django 5.1.7 on 2025-04-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0005_wishlist_created_at_wishlist_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={"verbose_name": "Wishlist", "verbose_name_plural": "Wishlists"},
        ),
        migrations.RenameField(
            model_name="wishlist",
            old_name="book",
            new_name="books",
        ),
    ]
